In [1]:
# Numpy
# . A library for Python, adding support for large , multi-dimensional arrays and matrices.
# . Provides a large collection of high-level mathematical functions to operates on arrays.
# . Numpy gives the functionality comparable to matlab since they are both interpreted and 
#   allow user  to write fast programs for operations on arrays or matrices.

In [2]:
# Numpy.ndarray
# . The main object of Numpy
# . Homogeneous multi-dimensional array
# . Index by a tuple of positive indexes or array like index
# . Attribute of numpy.ndarray
#   . ndim : the number of axes (dimension) of the ndarray
#   . shape: The dimensions of the array, returns a tuple describing each dimension
#   . size : total elements in the ndarray
#   . dtype: the data type of the elements in the ndarray. As ndarray is a homogeneous array, 
#            all elements in the ndarray should be the same type
#   . itemsize: the size in byte of each element in the ndarray.

In [3]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int32
4


In [4]:
# Array Creation 

In [5]:
# . Create ndarray from python data structure
# . Use np.array()

import numpy as np
a = np.array([2,3,4])
print(a)
print(a.dtype)

b = np.array([1.2, 3.5, 4.3])
print(b)
print(b.dtype)

[2 3 4]
int32
[1.2 3.5 4.3]
float64


In [6]:
# . You can also use tuple
a = np.array((1,2,3))
print(a)
print(a.dtype)

# . A frequent error
a = np.array(1,2,3,4)


[1 2 3]
int32


ValueError: only 2 non-keyword arguments accepted

In [7]:
# . numpy.array() transforms sequences of sequences into two-dimensional arrays, 
#   sequences of sequences of sequences into three-dimensional arrays, and so on.

a = np.array([[1,2,3], [4,5,6]])
print(a.shape)
print(a.dtype)
print(a)
print('-----')

a = np.array([  [[1,2,3],[4,5,6]],  [[7,8,9],[10,11,12]] ])
print(a.shape)
print(a.dtype)
print(a)


(2, 3)
int32
[[1 2 3]
 [4 5 6]]
-----
(2, 2, 3)
int32
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
# . You can even mix lists and tuples
a = np.array( [(1,2,3), [4,5,6]] )
print(a.shape)
print(a.dtype)
print(a)
print('--------------')
a = np.array((  [ (1,2,3),[4,5,6] ], [[7,8,9],(10,11,12)]   ))
print(a.shape)
print(a.dtype)
print(a)


(2, 3)
int32
[[1 2 3]
 [4 5 6]]
--------------
(2, 2, 3)
int32
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
# . The tye of the array can also be explicitly specified at runtime
c = np.array( [[1,2],[3,4]], dtype = complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [10]:
# . Also, there are some  useful functions to create array
# . numpy.zeros()

z = np.zeros((2,3))
print(z)

z = np.zeros(2,3)
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


TypeError: data type not understood

In [11]:
# . numpy.ones()
# . nmpy.empty()
print(np.ones([2,3]))
print(np.empty([2,3]))
print(np.zeros([2,3]))
print(np.empty([2,3]))





[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# . numpy.arrang( [start,] stop, [step,] dtype=None)
#   . Works like the range() function in python2, returns a ndarray
#   . Accept float number as input
print( np.arange(10,30,5) )

print( np.arange(0, 2, 0.3))

print( np.arange(10, 30, 5, dtype = float))


[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[10. 15. 20. 25.]


In [13]:
# . Generally, we can not predict the number of output when using floating 
#   point as the input of arange() due to the finite percision
# . numpy.linspace(start, end, num, ...)
print( np.linspace(0, 10, 11, dtype=int) )
print( np.linspace(0,2,10) )

[ 0  1  2  3  4  5  6  7  8  9 10]
[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [14]:
# . numpy.logspace( start, end, num, base = 10)
#   . Does the same thing as linspaceon log scale
print( np.logspace(1,3,3) )
print( np.logspace(1,3,3, base = 2) )
print( np.logspace(1,3,5, base = 2) )
print( np.logspace(1,3,5, base = 2, dtype = int) )

[  10.  100. 1000.]
[2. 4. 8.]
[2.         2.82842712 4.         5.65685425 8.        ]
[2 2 4 5 8]


In [15]:
# . numpy.meshgrid()
# . Make N-D coordinate arrays for vectorized evaluations of N-D 
#   scalar/vector fields over N-D grids, given one-dimensional coordinate arrays
print ('------ x ')
x = np.arange(-1,1,1)
print(x.shape)
print(x.dtype)
print(x)
print ('------ y ')
y = np.linspace(0, 2, 3)
print(y.shape)
print(y.dtype)
print(y)
print ('------ meshgrid(x,y)')
grid = np.meshgrid(x,y)
print(type(grid)) # grid is a list
print(grid )

print ('------ each item in list of meshgrid(x,y)')
for item in grid:
    print(type(item))    
    print(item.shape)
    print(item.dtype)
    print(item)




------ x 
(2,)
int32
[-1  0]
------ y 
(3,)
float64
[0. 1. 2.]
------ meshgrid(x,y)
<class 'list'>
[array([[-1,  0],
       [-1,  0],
       [-1,  0]]), array([[0., 0.],
       [1., 1.],
       [2., 2.]])]
------ each item in list of meshgrid(x,y)
<class 'numpy.ndarray'>
(3, 2)
int32
[[-1  0]
 [-1  0]
 [-1  0]]
<class 'numpy.ndarray'>
(3, 2)
float64
[[0. 0.]
 [1. 1.]
 [2. 2.]]


In [16]:
# . numpy.mgrid
#  . Work like meshgrid(), but not a function. Access via [] operator

mg = np.mgrid[1:3, -3:-1]
print(mg.shape)
print(mg.dtype)
print(mg)




(2, 2, 2)
int32
[[[ 1  1]
  [ 2  2]]

 [[-3 -2]
  [-3 -2]]]


In [17]:
# . numpy.ogrid
#   . Same as mgrid, except that the return value is flattened
og = np.ogrid[1:3, -3:-1]
print(type(og))
print(len(og))
print(og)
for i in og:
    print(i.shape)

<class 'list'>
2
[array([[1],
       [2]]), array([[-3, -2]])]
(2, 1)
(1, 2)


In [18]:
# . numpy.random.rand()
#   . Create an array with given shape and fill with samples 
#     from uniform distribution over [0,1)
print ( np.random.rand(3, 2) )

# . numpy.random.randn()
#   . Same as rand() except the distribution change to standard normal distribution
#   . For random sample from N(u,lo^2), use lo x np.random.rand()+u



[[0.53015317 0.41422949]
 [0.16028675 0.91461009]
 [0.17582486 0.56615709]]


In [19]:
# . numpy.fromfunction()
#   . Pass the coordinate of the point into the function and put the return value to the coordinate
def add(a,b):
    return a+b
print( np.fromfunction(add, (4,4)) )

print( np.fromfunction(lambda x,y:x, (4,4))  )

[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [20]:
# Array Indexing

In [21]:
# . Exactly like standard python sequence
x = np.arange(10)
print(x[2])
print(x[-2])

2
8


In [22]:
# . Also support multi-dimentional indexing
x.shape = (2,5)
print(x[1,3])
print(x[1,-1])
print(x[(1,1)])


8
9
6


In [23]:
#. If the index of multi-dimensional array is fewer than the dimension, then you gets the sub-dimension array
print(x)
print(x[0])

# Therefore, you can also access single element with 
print(x[0][1])

# However, this will be slight slower than x[0,1] since numpy will first create x[0] then access the second elements in x[0]


[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
1


In [24]:
# Other indexing options

In [25]:

# You can also get the sub-array of the same dimension with
x = np.arange(10)
print(x[2:5])
print(x[:-3])
print(x[1:8:2])



[2 3 4]
[0 1 2 3 4 5 6]
[1 3 5 7]


In [26]:
y = np.arange(35).reshape(5,7)
print(y)

print(y[1:5:2, ::3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[[ 7 10 13]
 [21 24 27]]


In [27]:
# The dots (...) represents as many colons to produce the complete index
# Assume x is a 5 dimensions array, then

# CASE z[1,2,...] is the same as to  z[1,2,:,:,:]
z = np.arange(6**5).reshape(6,6,6,6,6)
print(z[1,2,...].shape)
print(z[1,2,:,:,:].shape)
print(z[1,2,...])

(6, 6, 6)
(6, 6, 6)
[[[1728 1729 1730 1731 1732 1733]
  [1734 1735 1736 1737 1738 1739]
  [1740 1741 1742 1743 1744 1745]
  [1746 1747 1748 1749 1750 1751]
  [1752 1753 1754 1755 1756 1757]
  [1758 1759 1760 1761 1762 1763]]

 [[1764 1765 1766 1767 1768 1769]
  [1770 1771 1772 1773 1774 1775]
  [1776 1777 1778 1779 1780 1781]
  [1782 1783 1784 1785 1786 1787]
  [1788 1789 1790 1791 1792 1793]
  [1794 1795 1796 1797 1798 1799]]

 [[1800 1801 1802 1803 1804 1805]
  [1806 1807 1808 1809 1810 1811]
  [1812 1813 1814 1815 1816 1817]
  [1818 1819 1820 1821 1822 1823]
  [1824 1825 1826 1827 1828 1829]
  [1830 1831 1832 1833 1834 1835]]

 [[1836 1837 1838 1839 1840 1841]
  [1842 1843 1844 1845 1846 1847]
  [1848 1849 1850 1851 1852 1853]
  [1854 1855 1856 1857 1858 1859]
  [1860 1861 1862 1863 1864 1865]
  [1866 1867 1868 1869 1870 1871]]

 [[1872 1873 1874 1875 1876 1877]
  [1878 1879 1880 1881 1882 1883]
  [1884 1885 1886 1887 1888 1889]
  [1890 1891 1892 1893 1894 1895]
  [1896 1897 1898 18

In [28]:
# CASE z[..., 3] is the same as to  z[:,:,:,:, 3]
z = np.arange(4**5).reshape(4,4,4,4,4)
print(z[..., 3].shape)
print(z[:,:,:,:,3].shape)
print(z[..., 3])

(4, 4, 4, 4)
(4, 4, 4, 4)
[[[[   3    7   11   15]
   [  19   23   27   31]
   [  35   39   43   47]
   [  51   55   59   63]]

  [[  67   71   75   79]
   [  83   87   91   95]
   [  99  103  107  111]
   [ 115  119  123  127]]

  [[ 131  135  139  143]
   [ 147  151  155  159]
   [ 163  167  171  175]
   [ 179  183  187  191]]

  [[ 195  199  203  207]
   [ 211  215  219  223]
   [ 227  231  235  239]
   [ 243  247  251  255]]]


 [[[ 259  263  267  271]
   [ 275  279  283  287]
   [ 291  295  299  303]
   [ 307  311  315  319]]

  [[ 323  327  331  335]
   [ 339  343  347  351]
   [ 355  359  363  367]
   [ 371  375  379  383]]

  [[ 387  391  395  399]
   [ 403  407  411  415]
   [ 419  423  427  431]
   [ 435  439  443  447]]

  [[ 451  455  459  463]
   [ 467  471  475  479]
   [ 483  487  491  495]
   [ 499  503  507  511]]]


 [[[ 515  519  523  527]
   [ 531  535  539  543]
   [ 547  551  555  559]
   [ 563  567  571  575]]

  [[ 579  583  587  591]
   [ 595  599  603  607]
  

In [29]:
z = np.arange(3**5).reshape(3,3,3,3,3)
# CASE z[1,...,2,:] is the same as to  z[1,:,:,2,:]
print(z[1,...,2,:].shape)
print(z[1,:,:,2,:].shape)
print(z[1,...,2,:])
print(z[1,:,:,2,:])


(3, 3, 3)
(3, 3, 3)
[[[ 87  88  89]
  [ 96  97  98]
  [105 106 107]]

 [[114 115 116]
  [123 124 125]
  [132 133 134]]

 [[141 142 143]
  [150 151 152]
  [159 160 161]]]
[[[ 87  88  89]
  [ 96  97  98]
  [105 106 107]]

 [[114 115 116]
  [123 124 125]
  [132 133 134]]

 [[141 142 143]
  [150 151 152]
  [159 160 161]]]


In [30]:
# Index Arrays
# . The index of a numpy array can also be an array or list
x = np.arange(10)
y = np.arange(1,8,2)
print(y)
print(x[y])
print(x[[1,3,4,5]])
print(x[[1,3,-4,-5]]) # negative index in index array is allowed

# . The result of index array is an array with the same shape as the index array, 
#   and with the type and values of the array being indexed.

[1 3 5 7]
[1 3 5 7]
[1 3 4 5]
[1 3 6 5]


In [31]:
# Boolean array index
# . A Boolean array can also be the index of an numpy array
# . A Boolean array can be created by 
x = np.arange(10)
A = x > 5
print(A.dtype)
print(A)

# . So we can also do
print(np.array([6,7,8,9]))

# . A boolean array leave only the elements whose index are true in the array

# . The Boolean array should be the same shape with the array indexed.
print('-------')
x = np.array([1., -1., -2., 3])
print(x)
A = x < 0 
print(A)
x[x < 0] += 20
print(x)
print('-------')
x = np.array([1., -1., -2., 3])
print(x)
A = x < 0 
print(x[A])
x[A] += 20 
print(x)


bool
[False False False False False False  True  True  True  True]
[6 7 8 9]
-------
[ 1. -1. -2.  3.]
[False  True  True False]
[ 1. 19. 18.  3.]
-------
[ 1. -1. -2.  3.]
[-1. -2.]
[ 1. 19. 18.  3.]


In [32]:
# Iterate through the array


In [33]:
# . If we simply iterate through the array elements, the array wil be sliced along the first dimension.
x = np.arange(35).reshape(5,7)
print(x)

for i in x:
    print(i)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[0 1 2 3 4 5 6]
[ 7  8  9 10 11 12 13]
[14 15 16 17 18 19 20]
[21 22 23 24 25 26 27]
[28 29 30 31 32 33 34]


In [34]:
# . What if we want to iterate through each element in the array?
# . The flat attribute provide the iterator needed
for i in x.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34


In [35]:
# Basic array operations


In [36]:
# . Arithmetic operators on array apply element-wise. A new array is created and filled with the results.
a = np.array([20,30,40,50])
b = np.arange(1,5)
print(a + b)
print(a * b)
print(a / b)
print(a** b)
print(np.sin(a))

[21 32 43 54]
[ 20  60 120 200]
[20.         15.         13.33333333 12.5       ]
[     20     900   64000 6250000]
[ 0.91294525 -0.98803162  0.74511316 -0.26237485]


In [37]:
# . Arry shape mismatch results in error.  The following is the such example. 
x = np.arange(10)
y = np.arange(4)
print(x + y)

ValueError: operands could not be broadcast together with shapes (10,) (4,) 

In [38]:
# . Matrix multiplication
# . The * operator on two array applies element-wise
# . The dot() function performs matrix multiplication
x = np.array([[0,1],[2,3]])
y = np.array([[3,2],[1,0]])
print(x)

print( x * y )

print(x.dot(y))

print(x)

[[0 1]
 [2 3]]
[[0 2]
 [2 0]]
[[1 0]
 [9 4]]
[[0 1]
 [2 3]]


In [39]:
# . When operating with arrays of different types, the type of the resulting 
#   array corresponds to the more general or precise one.

x = np.arange(10)
y = np.arange(10,0,-1, dtype = float)
z = x * y 
print(z.dtype)

z = np.exp(x * 1j)
print(z)

print(z.dtype)

float64
[ 1.        +0.        j  0.54030231+0.84147098j -0.41614684+0.90929743j
 -0.9899925 +0.14112001j -0.65364362-0.7568025 j  0.28366219-0.95892427j
  0.96017029-0.2794155 j  0.75390225+0.6569866 j -0.14550003+0.98935825j
 -0.91113026+0.41211849j]
complex128


In [40]:
# Some functions


In [41]:
# . Unary functions
x = np.random.rand(10)
print(x)

print(x.max())
print(x.min())
print(x.std())

[0.99396979 0.00994197 0.44571215 0.2908365  0.48037245 0.28407653
 0.76517842 0.93617116 0.12795005 0.29104232]
0.9939697919554427
0.00994196726804486
0.3172496571985559


In [42]:
print( np.exp(x) ) 
print('---')
print( np.sin(x) )
print('---')
print( np.log(x) )
print('---')

[2.70193935 1.00999155 1.56160189 1.33754588 1.61667642 1.3285346
 2.14937783 2.5501984  1.13649624 1.33782121]
---
[0.83819757 0.0099418  0.43110056 0.2867537  0.4621095  0.28027111
 0.6926657  0.80529398 0.12760122 0.28695087]
---
[-0.00604846 -4.61099036 -0.80808194 -1.23499402 -0.73319354 -1.25851161
 -0.26764624 -0.06595696 -2.05611531 -1.23428658]
---


In [43]:
# Array shape modification


In [44]:
import numpy as np
x = np.arange(20).reshape(5,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [45]:
# . The ravel function returns a flatten array
print(x.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [46]:
y = x.reshape(2,10)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [47]:
# . The attribute T is the transpose of the array
print(x.T)

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


In [48]:
# . Previous operations returns a new array without modify the current one
# . The resize array change the shape of current array>>>x.resize(5,4)
x.resize(5,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [49]:
# . Also, you can change the shape of the array directly
x.shape = (4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [50]:
# Broadcasting 


In [51]:
# . Broadcasting means how numpy treats arrays with different shapes during arithmetic operations

# . Broadcasting provides a means of vectorizing array operations, so that looping occurs in C instread of Python

# . It does this without making needless copies of data and usually leads to efficient algorithm implemenetations.

# . Operations are usually done on equal shape array elementwise

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a*b)

b = 2 
print(a * b)

[ 4 10 18]
[2 4 6]


In [52]:
# . When operating on two arrays, NumPy compares their shapes element-wise. 
#   It starts with the trailing dimensions, and work its way forward.

# . Two dimensions are compatible when 
#   (1) they are equal,
#   (2) one of them are 1
#   (3) Else, the ValueError is raised
#   (4) Broadcasting lines up the compatible dimensions, for example, 
#       when you want to scale each color in a 256*256 RGB image



In [53]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))
print('x.shape=',x.shape)
print('y.shape=',y.shape)

x.shape= (4,)
y.shape= (5,)


In [54]:
x+y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [55]:
print('xx.shape=',xx.shape)
print('y.shape=',y.shape)
print('(xx+y).shape=',(xx+y).shape)
print('xx=\n',xx)
print('y=\n',y)
print('xx+y=\n',xx+y)

xx.shape= (4, 1)
y.shape= (5,)
(xx+y).shape= (4, 5)
xx=
 [[0]
 [1]
 [2]
 [3]]
y=
 [1. 1. 1. 1. 1.]
xx+y=
 [[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [69]:
print('x.shape=',x.shape)
print('z.shape=',z.shape)
print('(x+z).shape=',(x+z).shape)
print('x=\n', x)
print('z=\n', z)
print('x+z=\n',x+z)

x.shape= (4,)
z.shape= (3, 4)
(x+z).shape= (3, 4)
x=
 [0 1 2 3]
z=
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
x+z=
 [[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [85]:
# . Here the newaxis index operator inserts a new axis into a, 
#   making it a two-dimensional 4x1 array. Combining the 4x1 array with b, which 
#   has shape (3,), yields a 4x3 array.

a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
A = a[:, np.newaxis] 

print(a)
print(A)
print(a.shape)
print(A.shape)

print(A.T.shape)
print(A.T)

print(a[:, np.newaxis] + b)


[ 0. 10. 20. 30.]
[[ 0.]
 [10.]
 [20.]
 [30.]]
(4,)
(4, 1)
(1, 4)
[[ 0. 10. 20. 30.]]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
