In [1]:
# Numpy
# . A library for Python, adding support for large , multi-dimensional arrays and matrices.
# . Provides a large collection of high-level mathematical functions to operates on arrays.
# . Numpy gives the functionality comparable to matlab since they are both interpreted and 
#   allow user  to write fast programs for operations on arrays or matrices.

In [2]:
# Numpy.ndarray
# . The main object of Numpy
# . Homogeneous multi-dimensional array
# . Index by a tuple of positive indexes or array like index
# . Attribute of numpy.ndarray
#   . ndim : the number of axes (dimension) of the ndarray
#   . shape: The dimensions of the array, returns a tuple describing each dimension
#   . size : total elements in the ndarray
#   . dtype: the data type of the elements in the ndarray. As ndarray is a homogeneous array, 
#            all elements in the ndarray should be the same type
#   . itemsize: the size in byte of each element in the ndarray.

In [3]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int32
4


In [4]:
# Array Creation 

In [5]:
# . Create ndarray from python data structure
# . Use np.array()

import numpy as np
a = np.array([2,3,4])
print(a)
print(a.dtype)

b = np.array([1.2, 3.5, 4.3])
print(b)
print(b.dtype)

[2 3 4]
int32
[1.2 3.5 4.3]
float64


In [6]:
# . You can also use tuple
a = np.array((1,2,3))
print(a)
print(a.dtype)

# . A frequent error
a = np.array(1,2,3,4)


[1 2 3]
int32


ValueError: only 2 non-keyword arguments accepted

In [7]:
# . numpy.array() transforms sequences of sequences into two-dimensional arrays, 
#   sequences of sequences of sequences into three-dimensional arrays, and so on.

a = np.array([[1,2,3], [4,5,6]])
print(a.shape)
print(a.dtype)
print(a)
print('-----')

a = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(a.shape)
print(a.dtype)
print(a)


(2, 3)
int32
[[1 2 3]
 [4 5 6]]
-----
(2, 2, 3)
int32
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
