In [1]:
# Numpy
# . A library for Python, adding support for large , multi-dimensional arrays and matrices.
# . Provides a large collection of high-level mathematical functions to operates on arrays.
# . Numpy gives the functionality comparable to matlab since they are both interpreted and 
#   allow user  to write fast programs for operations on arrays or matrices.

In [2]:
# Numpy.ndarray
# . The main object of Numpy
# . Homogeneous multi-dimensional array
# . Index by a tuple of positive indexes or array like index
# . Attribute of numpy.ndarray
#   . ndim : the number of axes (dimension) of the ndarray
#   . shape: The dimensions of the array, returns a tuple describing each dimension
#   . size : total elements in the ndarray
#   . dtype: the data type of the elements in the ndarray. As ndarray is a homogeneous array, 
#            all elements in the ndarray should be the same type
#   . itemsize: the size in byte of each element in the ndarray.

In [3]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int32
4


In [4]:
# Array Creation 

In [5]:
# . Create ndarray from python data structure
# . Use np.array()

import numpy as np
a = np.array([2,3,4])
print(a)
print(a.dtype)

b = np.array([1.2, 3.5, 4.3])
print(b)
print(b.dtype)

[2 3 4]
int32
[1.2 3.5 4.3]
float64


In [6]:
# . You can also use tuple
a = np.array((1,2,3))
print(a)
print(a.dtype)

# . A frequent error
a = np.array(1,2,3,4)


[1 2 3]
int32


ValueError: only 2 non-keyword arguments accepted

In [7]:
# . numpy.array() transforms sequences of sequences into two-dimensional arrays, 
#   sequences of sequences of sequences into three-dimensional arrays, and so on.

a = np.array([[1,2,3], [4,5,6]])
print(a.shape)
print(a.dtype)
print(a)
print('-----')

a = np.array([  [[1,2,3],[4,5,6]],  [[7,8,9],[10,11,12]] ])
print(a.shape)
print(a.dtype)
print(a)


(2, 3)
int32
[[1 2 3]
 [4 5 6]]
-----
(2, 2, 3)
int32
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
# . You can even mix lists and tuples
a = np.array( [(1,2,3), [4,5,6]] )
print(a.shape)
print(a.dtype)
print(a)
print('--------------')
a = np.array((  [ (1,2,3),[4,5,6] ], [[7,8,9],(10,11,12)]   ))
print(a.shape)
print(a.dtype)
print(a)


(2, 3)
int32
[[1 2 3]
 [4 5 6]]
--------------
(2, 2, 3)
int32
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
# . The tye of the array can also be explicitly specified at runtime
c = np.array( [[1,2],[3,4]], dtype = complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [10]:
# . Also, there are some  useful functions to create array
# . numpy.zeros()

z = np.zeros((2,3))
print(z)

z = np.zeros(2,3)
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


TypeError: data type not understood

In [11]:
# . numpy.ones()
# . nmpy.empty()
print(np.ones([2,3]))
print(np.empty([2,3]))
print(np.zeros([2,3]))
print(np.empty([2,3]))





[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# . numpy.arrang( [start,] stop, [step,] dtype=None)
#   . Works like the range() function in python2, returns a ndarray
#   . Accept float number as input
print( np.arange(10,30,5) )

print( np.arange(0, 2, 0.3))

print( np.arange(10, 30, 5, dtype = float))


[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[10. 15. 20. 25.]


In [13]:
# . Generally, we can not predict the number of output when using floating 
#   point as the input of arange() due to the finite percision
# . numpy.linspace(start, end, num, ...)
print( np.linspace(0, 10, 11, dtype=int) )
print( np.linspace(0,2,10) )

[ 0  1  2  3  4  5  6  7  8  9 10]
[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [14]:
# . numpy.logspace( start, end, num, base = 10)
#   . Does the same thing as linspaceon log scale
print( np.logspace(1,3,3) )
print( np.logspace(1,3,3, base = 2) )
print( np.logspace(1,3,5, base = 2) )
print( np.logspace(1,3,5, base = 2, dtype = int) )

[  10.  100. 1000.]
[2. 4. 8.]
[2.         2.82842712 4.         5.65685425 8.        ]
[2 2 4 5 8]


In [15]:
# . numpy.meshgrid()
# . Make N-D coordinate arrays for vectorized evaluations of N-D 
#   scalar/vector fields over N-D grids, given one-dimensional coordinate arrays
print ('------ x ')
x = np.arange(-1,1,1)
print(x.shape)
print(x.dtype)
print(x)
print ('------ y ')
y = np.linspace(0, 2, 3)
print(y.shape)
print(y.dtype)
print(y)
print ('------ meshgrid(x,y)')
grid = np.meshgrid(x,y)
print(type(grid)) # grid is a list
print(grid )

print ('------ each item in list of meshgrid(x,y)')
for item in grid:
    print(type(item))    
    print(item.shape)
    print(item.dtype)
    print(item)




------ x 
(2,)
int32
[-1  0]
------ y 
(3,)
float64
[0. 1. 2.]
------ meshgrid(x,y)
<class 'list'>
[array([[-1,  0],
       [-1,  0],
       [-1,  0]]), array([[0., 0.],
       [1., 1.],
       [2., 2.]])]
------ each item in list of meshgrid(x,y)
<class 'numpy.ndarray'>
(3, 2)
int32
[[-1  0]
 [-1  0]
 [-1  0]]
<class 'numpy.ndarray'>
(3, 2)
float64
[[0. 0.]
 [1. 1.]
 [2. 2.]]


In [16]:
# . numpy.mgrid
#  . Work like meshgrid(), but not a function. Access via [] operator

mg = np.mgrid[1:3, -3:-1]
print(mg.shape)
print(mg.dtype)
print(mg)




(2, 2, 2)
int32
[[[ 1  1]
  [ 2  2]]

 [[-3 -2]
  [-3 -2]]]


In [17]:
# . numpy.ogrid
#   . Same as mgrid, except that the return value is flattened
og = np.ogrid[1:3, -3:-1]
print(type(og))
print(len(og))
print(og)
for i in og:
    print(i.shape)

<class 'list'>
2
[array([[1],
       [2]]), array([[-3, -2]])]
(2, 1)
(1, 2)


In [18]:
# . numpy.random.rand()
#   . Create an array with given shape and fill with samples 
#     from uniform distribution over [0,1)
print ( np.random.rand(3, 2) )

# . numpy.random.randn()
#   . Same as rand() except the distribution change to standard normal distribution
#   . For random sample from N(u,lo^2), use lo x np.random.rand()+u



[[0.10174762 0.9729758 ]
 [0.08762427 0.34139556]
 [0.70166088 0.20630486]]


In [19]:
# . numpy.fromfunction()
#   . Pass the coordinate of the point into the function and put the return value to the coordinate
def add(a,b):
    return a+b
print( np.fromfunction(add, (4,4)) )

print( np.fromfunction(lambda x,y:x, (4,4))  )

[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [20]:
# Array Indexing

In [21]:
# . Exactly like standard python sequence
x = np.arange(10)
print(x[2])
print(x[-2])

2
8


In [22]:
# . Also support multi-dimentional indexing
x.shape = (2,5)
print(x[1,3])
print(x[1,-1])
print(x[(1,1)])


8
9
6


In [24]:
#. If the index of multi-dimensional array is fewer than the dimension, then you gets the sub-dimension array
print(x)
print(x[0])

# Therefore, you can also access single element with

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
